kind: Service
apiVersion: v1
metadata:
  name: react-service-deployment
spec:
  type: NodePort
  selector:
    app: react-service
  ports:
  - protocol: TCP
    port: 8080
    nodePort: 31000

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: react-service-deployment
  labels:
    app: react-service
spec:
  replicas: 3
  selector:
    matchLabels:
      app: react-service
  template:
    metadata:
      labels:
        app: react-service
    spec:
      containers:
      - name: react-service
        image: $DOCKER_IMAGE_NAME:$BUILD_NUMBER
        ports:
        - containerPort: 8080
